Feature/react
evgeniymin/project3 pull request #1
Opened 2023-07-22 07:50 UTC by evgeniymin

2023-07-23 15:57 UTC, seniorjoinu commented
Так, начинаю комментировать. 
Перво-наперво - молодец. Хорошая работа. Но есть несколько недочетов.

1. Не нужно коммитить папку `node_modules`, потому что 
 - она занимает кучу дискового пространства
 - она мешает делать ревью, потому что гит думает, что это все файлы, которые изменились и их надо проверить
 - она не нужна тому, кто будет запускать твой проект у себя на компьютере, потому что `npm`, при запуске `npm i` выкачает эту папку из репозиториев сам

Таким образом, надо эту папку убрать. Это можно сделать [как написано здесь](https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode). А на будущее - используй файл `.gitignore` - в него можно добавлять файлы и папки (в том числе по glob-паттерну, чтобы рекурсивно игнорить). Это такой специальный файл, где ты перечисляешь все то, что не должно попасть в репозиторий ни при каких обстоятельствах и даже если ты сделаешь `git commit .`, то перечисленные имена в него не попадут.

2. Это мелочь, но тоже имей ввиду на будущее. Ты правильно сделал, что на английском коммиты называешь, это хорошо. Но пиши их так, будто они в повелительном наклонении (как будто ты просишь кого-то сделать тот или иной чендж). Вместо прошедшего времени, используй настоящее. Пиши с маленькой буквы. И пиши более развернуто. Не только "поменял вот это", а описывай, что именно поменял и почему. Кратко. Например, у тебя есть `Photoshopped Photos1.png`, вместо этого лучше так: `edit Photos1.png to make it look cooler`.

2023-07-23 15:59 UTC, seniorjoinu commented
3. Не замечание, а вопрос. А почему у тебя папка `node_modules` как-то отдельно от остального репозитория? Она же должна автоматически создаваться там же, где `package.json` лежит. Это ты сам сделал или `react-scripts` так работает?

2023-07-23 16:02 UTC, seniorjoinu commented on my-app/README.md
> +# Getting Started with Create React App
Этот файл нужен для того, чтобы описать проект для человека, который в первый раз его видит. 
Сейчас можно не менять ничего, но на будущее знай, что в нем надо что-то бы написать для других людей. Типа "Это моя имплементация игры крестики-нолики. Она работает так-то так-то. Чтобы её запустить нужно сделать то и то, запустить вот эти команды. Если что-то пошло не так, то вот как это можно решить. Если хотите что-то добавить в эту игру, то вот как это можно сделать."

Кстати, если ты поместишь этот файл в корень репозитория, то он будет красиво отрисовываться в гитхабе.

2023-07-23 19:50 UTC, evgeniymin commented
> Так, начинаю комментировать. Перво-наперво - молодец. Хорошая работа. Но есть несколько недочетов.
> 
> 1. Не нужно коммитить папку `node_modules`, потому что
> 
> * она занимает кучу дискового пространства
> * она мешает делать ревью, потому что гит думает, что это все файлы, которые изменились и их надо проверить
> * она не нужна тому, кто будет запускать твой проект у себя на компьютере, потому что `npm`, при запуске `npm i` выкачает эту папку из репозиториев сам
> 
> Таким образом, надо эту папку убрать. Это можно сделать [как написано здесь](https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode). А на будущее - используй файл `.gitignore` - в него можно добавлять файлы и папки (в том числе по glob-паттерну, чтобы рекурсивно игнорить). Это такой специальный файл, где ты перечисляешь все то, что не должно попасть в репозиторий ни при каких обстоятельствах и даже если ты сделаешь `git commit .`, то перечисленные имена в него не попадут.
> 
> 2. Это мелочь, но тоже имей ввиду на будущее. Ты правильно сделал, что на английском коммиты называешь, это хорошо. Но пиши их так, будто они в повелительном наклонении (как будто ты просишь кого-то сделать тот или иной чендж). Вместо прошедшего времени, используй настоящее. Пиши с маленькой буквы. И пиши более развернуто. Не только "поменял вот это", а описывай, что именно поменял и почему. Кратко. Например, у тебя есть `Photoshopped Photos1.png`, вместо этого лучше так: `edit Photos1.png to make it look cooler`.

Спасибо, 1. понял, убрал как там. 2. Окей, буду писать с маленькой буквы, использовать настоящее время и более подробно описывать, еще раз спасибо

2023-07-23 19:51 UTC, evgeniymin commented on my-app/README.md
> +# Getting Started with Create React App
Знаю, много раз много чего скачивал тут, да и просто часто вижу ридми, буду в будущем писать так

2023-07-23 19:51 UTC, evgeniymin commented on my-app/README.md
> +# Getting Started with Create React App
там*

2023-07-24 09:46 UTC, seniorjoinu requested changes
Исправь, пожалуйста, перечисленное.

2023-07-24 09:46 UTC, seniorjoinu commented on my-app/src/App.js
> +      </h1>
Если тег и его содержимое влазят в одну строчку - нужно их держать в одной строчке.
Если не влазят, то есть правила форматирования. Ты их можешь сам погуглить, а можешь просто установить [prettier](https://prettier.io/) или какой-то экстеншн для vscode.

2023-07-24 09:46 UTC, seniorjoinu commented on my-app/src/App.test.js
> +import { render, screen } from '@testing-library/react';
Если тест ничего полезного не тестирует, его надо убрать. Тем более у тебя тут какой-то сгенерированный стандартный тест, который только обзор захламляет.

Вообще, про тесты мы с тобой как-нибудь потом поговорим. Это - классная тема, чтобы баги ловить, но пока рано еще.

2023-07-24 09:46 UTC, seniorjoinu commented on my-app/src/Game.js
> +  }, [xh, oh, checkDraw, checkWin]);
Не удаляй ничего, но ответь: зачем `checkDraw` и `checkWin` добавил в зависимости к эффекту? 
Сколько раз за одну отрисовку этого компонента запустится этот эффект и почему?

2023-07-24 09:46 UTC, seniorjoinu commented on my-app/src/Game.js
> +      cell.classList.remove('disabled', 'x', 'o');
Смотри, если ты работаешь через React, то так делать нельзя. Когда ты так делаешь, ты идешь в обход virtual dom. Это может привести к тому, что html не будет обновляться, когда ты от него это требуешь.

Тебе надо эту строчку удалить и сделать так, чтобы реакт сам сбросил css классы у ячеек. Подсказка: `className` - это обычное реакт-свойство. В него можно засунуть кусочек реакт-стейта, созданного с помощью `useState`.

2023-07-24 09:46 UTC, seniorjoinu commented on my-app/src/Game.js
> +      cell.classList.remove('disabled', 'x', 'o');
То же самое относится ко всей функции `handleClick` - там ты тоже напрямую через dom api взаимодействуешь со страницей, а не через react. Надо переделать её.

2023-07-24 09:46 UTC, seniorjoinu commented on my-app/src/main.jsx
> +import React from "react";
В чем отличие от index.js? Зачем их два? Какой именно подгружается на страницу?

2023-07-26 19:41 UTC, evgeniymin commented on my-app/src/App.js
> +      </h1>
Понял, после того как исправлю остальное сделаю коммит, может установлю чуть позже.

2023-07-26 19:49 UTC, evgeniymin commented on my-app/src/App.test.js
> +import { render, screen } from '@testing-library/react';
Он сам сгенерировался с реакт скриптс, уберу

2023-07-29 21:36 UTC, evgeniymin commented on my-app/src/Game.js
> +  }, [xh, oh, checkDraw, checkWin]);
Просто что бы исключить баги какие-нибудь если вдруг checkDraw или checkWin как-то изменяться, и у меня одно из расширений ругалось, за одну отрисовку компонента эффект запустится получается 1 раз, потому что в нем же нету ничего что меняло бы переменные и получается он запустится 1 раз только в самом начале в отрисовке, и потом будет запускаться только уже когда сделают ходы или будет победа/ничья.

2023-07-29 21:38 UTC, evgeniymin commented on my-app/src/main.jsx
> +import React from "react";
Я делал все по тому времени когда видел как это сделать в видеоуроке, index.js был создан автоматически, а на видеоуроке об этом не сказали.

2023-08-09 10:57 UTC, seniorjoinu commented on my-app/src/Game.js
> +  }, [xh, oh, checkDraw, checkWin]);
Смотри, `Game` - это просто функция. Когда ты её реакту передаешь в JSX (когда пишешь `<Game/>` где-то в верстке), реакт её сразу не запускает. Но потом, когда у него начинается цикл отрисовки, он эту функцию запустит. `checkDraw`, `handleClick` и другие переменные (за исключением тех, что ты создаешь с `useState`) - это просто локальные для функции объекты. Каждый раз, когда функция запускается, они создаются заново. Функция запускается на каждой перерисовке. Это значит, что и объекты эти создаются заново на каждой перерисовке. Это значит, что и эффект будет срабатывать на каждой перерисовке, потому что объекты, которые ты туда передаешь в качестве зависимостей создаются заново = меняются. 

https://stackoverflow.com/questions/62601538/passing-a-function-in-the-useeffect-dependency-array-causes-infinite-loop

Но я, на самом деле, задал этот вопрос еще и потому, что тебе не нужно передавать `checkDraw` и `checkWin` в зависимости к эффекту, потому что эти функции не меняются с течением времени (ты их никак не переопределяешь динамически - написал их один раз и так они и работают). Это значит, что даже если и ссылка на них меняется, то срабатывание эффекта будет пустым - потому что логика самой функции осталась прежней - значит и результат выполнения функции будет прежним и нет смысла его еще раз пересчитывать.

Зато вот `xh` и `oh` меняются. И от них как раз таки зависит результат - если один из этих параметров меняется, то результат всей функции тоже может поменяться. 

Это значит, что `checkDraw` и `checkWin` можно убрать, а `xh` и `oh` - надо оставить.

2023-08-10 09:56 UTC, seniorjoinu approved these changes
Воо, теперь все хорошо.
Молодец, можешь мержить это дело в master!

2023-08-11 16:59 UTC, merged